name: perfumer

services:
  go-api:
    restart: always
    build: ./go-api
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET=${GO_SECRET}
    expose:
      - "3000"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - cache
  frontend:
    restart: always
    build: ./frontend
    ports:
      - 80:80
    expose:
      - "80"
    depends_on:
      - go-api
    networks:
      - frontend
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - backend
  cache:
    restart: always
    image: redis:alpine
    expose:
      - 6379
    networks:
      - backend
  llm:
    restart: always
    build: ./llm
    expose:
      - 11434
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-db:
